### ISSUE TITLE
401 Unauthorized when I try to create connection on Ditto Explorer ui

### ISSUE THREAD

**Issue by Felice-Copp56** [eclipse-ditto/ditto#1533]
Hi, I have deployed Eclipse ditto on my k8s cluster with the helm chart, the ditto-nginx service gateway is up and running at localhost:8080. 
I can create policy, the thing but when I try to create connection for MQTT with js mapping in the Ditto explorer ui I got a 401 unauthorized error, I have used devops and foobar credentials.
Also, I have tried to create the connection via curl command on bash  by following this tutorial https://github.com/eclipse-ditto/ditto-examples/blob/master/mqtt-bidirectional/README.md, in this case MQTT pub and sub works on the bash but on my web browser I can't see any update of my device.
Any idea?

**Comment by thfries** [comment]
Hi @Felice-Copp56,
for the UI error, please check if you provided the right user for the connections api:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/20593339/201481110-8bfebe5d-20e0-4228-b641-ffc058fe8676.png">

There is no tutorial for setting up your case with the UI. Here are the steps I tried:

1. Create the MQTT 5 with JS Mapping connection
2. Set the connection status to "open" and save the connection. Be sure the live connection status turns open: 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/20593339/201482660-ca0a397b-b2c8-43c1-9306-d91f39762551.png">

3. (optional) Enable connection logs on the connection: 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/20593339/201482714-baa37034-ae27-4630-861d-4af5e1ba2201.png">
 
4. Create an empty thing: 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/20593339/201482784-418a2ffe-3529-44f3-9d80-d1bee961453a.png">

5. Adjust the policy of the thing and allow the MQTT connection to access it. Add a new entry "MQTT" to the policy and add the two authorization subjects of the connection to the entry: 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/20593339/201482952-71a68dee-89f6-41ed-9972-a9fe67bc8edc.png">

6. On your MQTT client, create a sample ditto message in a file `message.json` (adapt the ID of your thing created in step 4):

```
{
  "topic": "org.eclipse.ditto/7dab7c0f-67e5-423c-a859-ed7982699788/things/twin/commands/modify",
  "path": "/attributes/serialNumber",
  "value": 123456789
}
```

8. Publish that message to the MQTT broker:
`mosquitto_pub -h test.mosquitto.org -p 1883 -t eclipse-ditto-sandbox/7dab7c0f-67e5-423c-a859-ed7982699788/update -D publish content-type application/vnd.eclipse.ditto+json -f message.json`

9. Message is processed and the thing should have a new serial number attribute: 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/20593339/201483649-eed03b7c-cbf9-4d2a-8be7-6833ac0d3ef1.png">

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/20593339/201483691-f95d3ca7-1edf-4cd8-9108-526929c3eb7c.png">

Let me know if that works for you. Be sure to separate namespace and thingName in the message payload and topic names in the right way.
In the other example, the connection just uses the `nginx:ditto` authorization subject. So instead of changing the policy (step 5), you can also change the authorization subjects in the connection from `ditto:inbound-auth-subject` to `nginx:ditto` (same for `ditto:outbound-auth-subject`). The way described above is a bit more complicated but mimics a real scenario where you control independent access rights for the device and the application.

**Comment by thfries** [comment]
To complete the "bi-directional" example: For the cloud to device communication first option is to set a **desired state of a feature**:


1. On your MQTT client, execute: `mosquitto_sub -h test.mosquitto.org -p 1883 -t eclipse-ditto-sandbox/#`

2. Create a new feature for your thing: 
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/20593339/201485274-e74a5cde-5486-489e-a63e-eec3af08eee5.png">

3. Your MQTT client should receive a message:
```
{
  "topic": "org.eclipse.ditto/7dab7c0f-67e5-423c-a859-ed7982699788/things/twin/events/created",
  "path": "/features/new-feature",
  "headers": ...,
  "value": {}
}
```

4. Set a desired state of the new feature: 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/20593339/201485581-30161482-c33c-42cc-acf5-db684f7ba52d.png">

5. Message received by the MQTT client:
```
{
  "topic": "org.eclipse.ditto/7dab7c0f-67e5-423c-a859-ed7982699788/things/twin/events/modified",
  "path": "/features/new-feature",
  "headers": ...,
  "value": {
    "desiredProperties": {
      "mode": "DEBUG"
    }
  }
}
```

Instead of using a desired state, you can also just **send a command to the device**:

1. On your new feature send a message with `timeout=0` (fire and forget): 
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/20593339/201489553-afdd2644-57fc-4bea-866d-dba277be71c5.png">

2. MQTT client receives this command as a live message:
```
{
  "topic": "org.eclipse.ditto/7dab7c0f-67e5-423c-a859-ed7982699788/things/live/messages/ENABLE_DEBUG_MODE",
  "path": "/features/new-feature/inbox/messages/ENABLE_DEBUG_MODE",
  "headers": ...,
  "value": "{}"
}
```

**Comment by thjaeckle** [comment]
@Felice-Copp56 did the provided answers by @thfries solve you problem?
Then a short feedback would be the polite thing to do ..

Thanks @thfries for jumping in ..
