### ISSUE TITLE
Multiple Ditto Services on several K8S nodes

### ISSUE THREAD

**Issue by LiuYangMrLY** [eclipse-ditto/ditto#1559]
After reading the offered documentation, I came upon a question that stumped me. If I deploy the external dependency MongoDB on several K8S nodes which can be considered as a single MongoDB, and deploy multiple Ditto on other nodes configured to use the single MongoDB, when a same request reaches different Ditto node, is the behavior (e.g., the data returned) same? If not, what is the different behavior and why?

P.S. Whether there are some solutions to deploy multiple Ditto Services on several K8S nodes?
Thank you.

**Comment by thjaeckle** [comment]
What do you mean with "deploy multiple Ditto on other nodes"?
As long as this is one Ditto cluster, you can scale out every single Ditto service (eg Ditto-things to as many instances as you require for handling your load).

Configuring several separate Ditto clusters to use the same MongoDB instance using the same collections is a really bad idea, the underlying event sourcing mechanism which Ditto makes use of will cause corrupt DB entries if eg the same Thing is updated by multiple Ditto installations.

Because of this, a blue/green update of Ditto is also not advisable.

**Comment by youxiho1** [comment]
> What do you mean with "deploy multiple Ditto on other nodes"? As long as this is one Ditto cluster, you can scale out every single Ditto service (eg Ditto-things to as many instances as you require for handling your load).
> 
> Configuring several separate Ditto clusters to use the same MongoDB instance using the same collections is a really bad idea, the underlying event sourcing mechanism which Ditto makes use of will cause corrupt DB entries if eg the same Thing is updated by multiple Ditto installations.
> 
> Because of this, a blue/green update of Ditto is also not advisable.

Hi, I'm also wondering about how to deploy a ditto cluster on several servers (via kubernetes). Ditto is the core component of my system, so I'm trying to prevent SPOF(single point of failure). I think I should deploy a ditto cluster on several servers (via kubernetes)? Or any other advice on how to achieve this goal?

I've read the document files but I didn't find a tutorial about scaling out ditto service/deploying ditto on several computers (to become a whole cluster). Am I lacking something important?

Thank for your help in advance!

**Comment by thjaeckle** [comment]
Sure, just deploy Ditto via kubernetes and adjust the scale to >1 per service/role.
There is nothing documented as this is common kubernetes basics.
