### ISSUE TITLE
Patching a thing with a null value in JSON body is not reflected in the UI in real time

### ISSUE THREAD

**Issue by kosta777** [eclipse-ditto/ditto#1712]
When sending a patch request to Ditto in a JSON merge patch format and using a null specifier to request a deletion of a JSON key from the thing, if said thing was already selected in the UI console, it does **not** get updated right away to reflect this removal. In order to see whether the removal happened, one needs to either refresh the page, or deselect and select the thing in question again.

Considering that adding or modifying things via patch requests results in the selected thing in the UI being updated right away, I suspect this could be a bug.

For example, a patch request with the following body would result in the updated "brewingTemp" being visible right away in the UI for the selected thing, but "brewed-coffees" would also be visible until a page is refreshed, or the thing was deselected and selected again.

```
{
    "features" : {
        "coffee-brewer":{
           "properties":{
               "brewed-coffees": null, //remove key
               "brewingTemp":87 //update value
           }
        }
    }
}
```

**Comment by thjaeckle** [comment]
Thanks for reporting, @kosta777 

I think that is due to the nature of Ditto's [Server Sent Event](https://eclipse.dev/ditto/httpapi-sse.html#sse-api-things) API which the Ditto UI makes use of.  
When something is deleted, the SSE will only get a notification like:
```json
{}
```

What could help is to provide some kind of optional "context" (e.g. with the original Ditto Protocol information) when subscribing to the SSE.
I will look into this ..
