### ISSUE TITLE
Modifying the MQTT topic within the Javascript mapping

### ISSUE THREAD

**Issue by michael-itq** [eclipse-ditto/ditto#2010]
We want to achive that the MQTT messages are published on a more detailled topic path.
E.g: myPrefix/myNamespace/myThing/attributes/myOwnAttribute

In the connection settings (Path: connection/targets/address) the mqtt topic is defined.
In this setting placehoders can be used (https://eclipse.dev/ditto/2.1/basic-placeholders.html#scope-connections).
Here you can define:
"address": "myPrefix/myNamespace/{{ thing:id }}"

But for the part "/attributes/myOwnAttribute" we could not find any solution:
- Placehoder for this informtion is not available
- Adding something to the header and using {{header:<header-name>}} seems only to work for existing headers. Headers which are added during runtime seem not to be supported for the mapping/placehoders.
- In the mapping functions mapFromDittoProtocolMsg/mapFromDittoProtocolMsgWrapper we did not find any possibility to directly change the MQTT topic

Is the changing of the MQTT topic basically possible?

**Comment by thjaeckle** [comment]
Hi.

For MQTT connections, you have special headers available to modify the MQTT topic of a `target`:
https://eclipse.dev/ditto/connectivity-protocol-bindings-mqtt.html#target-header-mapping
> * **mqtt.topic**: overwrites the topic configured for the target
> * **mqtt.qos**: overwrites the qos level configured for the target
> * **mqtt.retain**: controls whether the MQTT retain flag is set on the published message

This can be used in a custom provided [JavaScript payload mapper](https://eclipse.dev/ditto/connectivity-mapping.html#javascript-mapping-engine) in order to modify both MQTT topic and payload to publish on that topic.

So this is doable with custom scripting (the script is stored as part of the Ditto connection).
